version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
  python:
    build: .
    working_dir: /home/remote-dev/work
    volumes:
      - ./web/remote-dev/work:/home/remote-dev/work/
    environment:
      TZ: 'Asia/Tokyo'
    tty: true
    ports:
      - 80:80
    depends_on:
      - db
